//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 01:03:34 AM EDT 
//


package org.mindinformatics.services.connector.pubmed.search;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mindinformatics.swan.pubmed.service.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mindinformatics.swan.pubmed.service.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RetStart }
     * 
     */
    public RetStart createRetStart() {
        return new RetStart();
    }

    /**
     * Create an instance of {@link Translation }
     * 
     */
    public Translation createTranslation() {
        return new Translation();
    }

    /**
     * Create an instance of {@link TranslationStack }
     * 
     */
    public TranslationStack createTranslationStack() {
        return new TranslationStack();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link OP }
     * 
     */
    public OP createOP() {
        return new OP();
    }

    /**
     * Create an instance of {@link FieldNotFound }
     * 
     */
    public FieldNotFound createFieldNotFound() {
        return new FieldNotFound();
    }

    /**
     * Create an instance of {@link Explode }
     * 
     */
    public Explode createExplode() {
        return new Explode();
    }

    /**
     * Create an instance of {@link WarningList }
     * 
     */
    public WarningList createWarningList() {
        return new WarningList();
    }

    /**
     * Create an instance of {@link TranslationSet }
     * 
     */
    public TranslationSet createTranslationSet() {
        return new TranslationSet();
    }

    /**
     * Create an instance of {@link QueryKey }
     * 
     */
    public QueryKey createQueryKey() {
        return new QueryKey();
    }

    /**
     * Create an instance of {@link TermSet }
     * 
     */
    public TermSet createTermSet() {
        return new TermSet();
    }

    /**
     * Create an instance of {@link OutputMessage }
     * 
     */
    public OutputMessage createOutputMessage() {
        return new OutputMessage();
    }

    /**
     * Create an instance of {@link ErrorList }
     * 
     */
    public ErrorList createErrorList() {
        return new ErrorList();
    }

    /**
     * Create an instance of {@link IdList }
     * 
     */
    public IdList createIdList() {
        return new IdList();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link Count }
     * 
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link QueryTranslation }
     * 
     */
    public QueryTranslation createQueryTranslation() {
        return new QueryTranslation();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link RetMax }
     * 
     */
    public RetMax createRetMax() {
        return new RetMax();
    }

    /**
     * Create an instance of {@link QuotedPhraseNotFound }
     * 
     */
    public QuotedPhraseNotFound createQuotedPhraseNotFound() {
        return new QuotedPhraseNotFound();
    }

    /**
     * Create an instance of {@link PhraseIgnored }
     * 
     */
    public PhraseIgnored createPhraseIgnored() {
        return new PhraseIgnored();
    }

    /**
     * Create an instance of {@link PhraseNotFound }
     * 
     */
    public PhraseNotFound createPhraseNotFound() {
        return new PhraseNotFound();
    }

    /**
     * Create an instance of {@link ESearchResult }
     * 
     */
    public ESearchResult createESearchResult() {
        return new ESearchResult();
    }

    /**
     * Create an instance of {@link WebEnv }
     * 
     */
    public WebEnv createWebEnv() {
        return new WebEnv();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link ERROR }
     * 
     */
    public ERROR createERROR() {
        return new ERROR();
    }

}
