//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 01:03:34 AM EDT 
//


package org.mindinformatics.services.connector.pubmed.fetch;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;




/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}Journal"/>
 *           &lt;element ref="{}Book"/>
 *         &lt;/choice>
 *         &lt;element ref="{}ArticleTitle"/>
 *         &lt;element ref="{}Pagination"/>
 *         &lt;element ref="{}Abstract" minOccurs="0"/>
 *         &lt;element ref="{}Affiliation" minOccurs="0"/>
 *         &lt;element ref="{}AuthorList" minOccurs="0"/>
 *         &lt;element ref="{}Language" maxOccurs="unbounded"/>
 *         &lt;element ref="{}DataBankList" minOccurs="0"/>
 *         &lt;element ref="{}GrantList" minOccurs="0"/>
 *         &lt;element ref="{}PublicationTypeList"/>
 *         &lt;element ref="{}VernacularTitle" minOccurs="0"/>
 *         &lt;element ref="{}ArticleDate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PubModel" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Electronic"/>
 *             &lt;enumeration value="Print"/>
 *             &lt;enumeration value="Electronic-Print"/>
 *             &lt;enumeration value="Print-Electronic"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journal",
    "book",
    "articleTitle",
    "pagination",
    "_abstract",
    "affiliation",
    "authorList",
    "language",
    "dataBankList",
    "grantList",
    "publicationTypeList",
    "vernacularTitle",
    "articleDate"
})
@XmlRootElement(name = "Article")
public class Article {

    @XmlElement(name = "Journal")
    protected Journal journal;
    @XmlElement(name = "Book")
    protected Book book;
    @XmlElement(name = "ArticleTitle", required = true)
    protected ArticleTitle articleTitle;
    @XmlElement(name = "Pagination", required = true)
    protected Pagination pagination;
    @XmlElement(name = "Abstract")
    protected Abstract _abstract;
    @XmlElement(name = "Affiliation")
    protected Affiliation affiliation;
    @XmlElement(name = "AuthorList")
    protected AuthorList authorList;
    @XmlElement(name = "Language", required = true)
    protected List<Language> language;
    @XmlElement(name = "DataBankList")
    protected DataBankList dataBankList;
    @XmlElement(name = "GrantList")
    protected GrantList grantList;
    @XmlElement(name = "PublicationTypeList", required = true)
    protected PublicationTypeList publicationTypeList;
    @XmlElement(name = "VernacularTitle")
    protected VernacularTitle vernacularTitle;
    @XmlElement(name = "ArticleDate")
    protected List<ArticleDate> articleDate;
    @XmlAttribute(name = "PubModel", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String pubModel;

    /**
     * Gets the value of the journal property.
     * 
     * @return
     *     possible object is
     *     {@link Journal }
     *     
     */
    public Journal getJournal() {
        return journal;
    }

    /**
     * Sets the value of the journal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Journal }
     *     
     */
    public void setJournal(Journal value) {
        this.journal = value;
    }

    /**
     * Gets the value of the book property.
     * 
     * @return
     *     possible object is
     *     {@link Book }
     *     
     */
    public Book getBook() {
        return book;
    }

    /**
     * Sets the value of the book property.
     * 
     * @param value
     *     allowed object is
     *     {@link Book }
     *     
     */
    public void setBook(Book value) {
        this.book = value;
    }

    /**
     * Gets the value of the articleTitle property.
     * 
     * @return
     *     possible object is
     *     {@link ArticleTitle }
     *     
     */
    public ArticleTitle getArticleTitle() {
        return articleTitle;
    }

    /**
     * Sets the value of the articleTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArticleTitle }
     *     
     */
    public void setArticleTitle(ArticleTitle value) {
        this.articleTitle = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * @return
     *     possible object is
     *     {@link Affiliation }
     *     
     */
    public Affiliation getAffiliation() {
        return affiliation;
    }

    /**
     * Sets the value of the affiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Affiliation }
     *     
     */
    public void setAffiliation(Affiliation value) {
        this.affiliation = value;
    }

    /**
     * Gets the value of the authorList property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorList }
     *     
     */
    public AuthorList getAuthorList() {
        return authorList;
    }

    /**
     * Sets the value of the authorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorList }
     *     
     */
    public void setAuthorList(AuthorList value) {
        this.authorList = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Language }
     * 
     * 
     */
    public List<Language> getLanguage() {
        if (language == null) {
            language = new ArrayList<Language>();
        }
        return this.language;
    }

    /**
     * Gets the value of the dataBankList property.
     * 
     * @return
     *     possible object is
     *     {@link DataBankList }
     *     
     */
    public DataBankList getDataBankList() {
        return dataBankList;
    }

    /**
     * Sets the value of the dataBankList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataBankList }
     *     
     */
    public void setDataBankList(DataBankList value) {
        this.dataBankList = value;
    }

    /**
     * Gets the value of the grantList property.
     * 
     * @return
     *     possible object is
     *     {@link GrantList }
     *     
     */
    public GrantList getGrantList() {
        return grantList;
    }

    /**
     * Sets the value of the grantList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrantList }
     *     
     */
    public void setGrantList(GrantList value) {
        this.grantList = value;
    }

    /**
     * Gets the value of the publicationTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationTypeList }
     *     
     */
    public PublicationTypeList getPublicationTypeList() {
        return publicationTypeList;
    }

    /**
     * Sets the value of the publicationTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationTypeList }
     *     
     */
    public void setPublicationTypeList(PublicationTypeList value) {
        this.publicationTypeList = value;
    }

    /**
     * Gets the value of the vernacularTitle property.
     * 
     * @return
     *     possible object is
     *     {@link VernacularTitle }
     *     
     */
    public VernacularTitle getVernacularTitle() {
        return vernacularTitle;
    }

    /**
     * Sets the value of the vernacularTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VernacularTitle }
     *     
     */
    public void setVernacularTitle(VernacularTitle value) {
        this.vernacularTitle = value;
    }

    /**
     * Gets the value of the articleDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleDate }
     * 
     * 
     */
    public List<ArticleDate> getArticleDate() {
        if (articleDate == null) {
            articleDate = new ArrayList<ArticleDate>();
        }
        return this.articleDate;
    }

    /**
     * Gets the value of the pubModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubModel() {
        return pubModel;
    }

    /**
     * Sets the value of the pubModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubModel(String value) {
        this.pubModel = value;
    }

}
