//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 01:03:34 AM EDT 
//


package org.mindinformatics.services.connector.pubmed.fetch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CommentOn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}CommentIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ErratumIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ErratumFor" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PartialRetractionIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PartialRetractionOf" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}RepublishedFrom" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}RepublishedIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}RetractionOf" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}RetractionIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}UpdateIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}UpdateOf" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}SummaryForPatientsIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}OriginalReportIn" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ReprintOf" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ReprintIn" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commentOn",
    "commentIn",
    "erratumIn",
    "erratumFor",
    "partialRetractionIn",
    "partialRetractionOf",
    "republishedFrom",
    "republishedIn",
    "retractionOf",
    "retractionIn",
    "updateIn",
    "updateOf",
    "summaryForPatientsIn",
    "originalReportIn",
    "reprintOf",
    "reprintIn"
})
@XmlRootElement(name = "CommentsCorrections")
public class CommentsCorrections {

    @XmlElement(name = "CommentOn")
    protected List<CommentOn> commentOn;
    @XmlElement(name = "CommentIn")
    protected List<CommentIn> commentIn;
    @XmlElement(name = "ErratumIn")
    protected List<ErratumIn> erratumIn;
    @XmlElement(name = "ErratumFor")
    protected List<ErratumFor> erratumFor;
    @XmlElement(name = "PartialRetractionIn")
    protected List<PartialRetractionIn> partialRetractionIn;
    @XmlElement(name = "PartialRetractionOf")
    protected List<PartialRetractionOf> partialRetractionOf;
    @XmlElement(name = "RepublishedFrom")
    protected List<RepublishedFrom> republishedFrom;
    @XmlElement(name = "RepublishedIn")
    protected List<RepublishedIn> republishedIn;
    @XmlElement(name = "RetractionOf")
    protected List<RetractionOf> retractionOf;
    @XmlElement(name = "RetractionIn")
    protected List<RetractionIn> retractionIn;
    @XmlElement(name = "UpdateIn")
    protected List<UpdateIn> updateIn;
    @XmlElement(name = "UpdateOf")
    protected List<UpdateOf> updateOf;
    @XmlElement(name = "SummaryForPatientsIn")
    protected List<SummaryForPatientsIn> summaryForPatientsIn;
    @XmlElement(name = "OriginalReportIn")
    protected List<OriginalReportIn> originalReportIn;
    @XmlElement(name = "ReprintOf")
    protected List<ReprintOf> reprintOf;
    @XmlElement(name = "ReprintIn")
    protected List<ReprintIn> reprintIn;

    /**
     * Gets the value of the commentOn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentOn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentOn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentOn }
     * 
     * 
     */
    public List<CommentOn> getCommentOn() {
        if (commentOn == null) {
            commentOn = new ArrayList<CommentOn>();
        }
        return this.commentOn;
    }

    /**
     * Gets the value of the commentIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commentIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommentIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommentIn }
     * 
     * 
     */
    public List<CommentIn> getCommentIn() {
        if (commentIn == null) {
            commentIn = new ArrayList<CommentIn>();
        }
        return this.commentIn;
    }

    /**
     * Gets the value of the erratumIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the erratumIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErratumIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErratumIn }
     * 
     * 
     */
    public List<ErratumIn> getErratumIn() {
        if (erratumIn == null) {
            erratumIn = new ArrayList<ErratumIn>();
        }
        return this.erratumIn;
    }

    /**
     * Gets the value of the erratumFor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the erratumFor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErratumFor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ErratumFor }
     * 
     * 
     */
    public List<ErratumFor> getErratumFor() {
        if (erratumFor == null) {
            erratumFor = new ArrayList<ErratumFor>();
        }
        return this.erratumFor;
    }

    /**
     * Gets the value of the partialRetractionIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partialRetractionIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartialRetractionIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartialRetractionIn }
     * 
     * 
     */
    public List<PartialRetractionIn> getPartialRetractionIn() {
        if (partialRetractionIn == null) {
            partialRetractionIn = new ArrayList<PartialRetractionIn>();
        }
        return this.partialRetractionIn;
    }

    /**
     * Gets the value of the partialRetractionOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partialRetractionOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartialRetractionOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartialRetractionOf }
     * 
     * 
     */
    public List<PartialRetractionOf> getPartialRetractionOf() {
        if (partialRetractionOf == null) {
            partialRetractionOf = new ArrayList<PartialRetractionOf>();
        }
        return this.partialRetractionOf;
    }

    /**
     * Gets the value of the republishedFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the republishedFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepublishedFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepublishedFrom }
     * 
     * 
     */
    public List<RepublishedFrom> getRepublishedFrom() {
        if (republishedFrom == null) {
            republishedFrom = new ArrayList<RepublishedFrom>();
        }
        return this.republishedFrom;
    }

    /**
     * Gets the value of the republishedIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the republishedIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepublishedIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepublishedIn }
     * 
     * 
     */
    public List<RepublishedIn> getRepublishedIn() {
        if (republishedIn == null) {
            republishedIn = new ArrayList<RepublishedIn>();
        }
        return this.republishedIn;
    }

    /**
     * Gets the value of the retractionOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retractionOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetractionOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetractionOf }
     * 
     * 
     */
    public List<RetractionOf> getRetractionOf() {
        if (retractionOf == null) {
            retractionOf = new ArrayList<RetractionOf>();
        }
        return this.retractionOf;
    }

    /**
     * Gets the value of the retractionIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retractionIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetractionIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetractionIn }
     * 
     * 
     */
    public List<RetractionIn> getRetractionIn() {
        if (retractionIn == null) {
            retractionIn = new ArrayList<RetractionIn>();
        }
        return this.retractionIn;
    }

    /**
     * Gets the value of the updateIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateIn }
     * 
     * 
     */
    public List<UpdateIn> getUpdateIn() {
        if (updateIn == null) {
            updateIn = new ArrayList<UpdateIn>();
        }
        return this.updateIn;
    }

    /**
     * Gets the value of the updateOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateOf }
     * 
     * 
     */
    public List<UpdateOf> getUpdateOf() {
        if (updateOf == null) {
            updateOf = new ArrayList<UpdateOf>();
        }
        return this.updateOf;
    }

    /**
     * Gets the value of the summaryForPatientsIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summaryForPatientsIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSummaryForPatientsIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SummaryForPatientsIn }
     * 
     * 
     */
    public List<SummaryForPatientsIn> getSummaryForPatientsIn() {
        if (summaryForPatientsIn == null) {
            summaryForPatientsIn = new ArrayList<SummaryForPatientsIn>();
        }
        return this.summaryForPatientsIn;
    }

    /**
     * Gets the value of the originalReportIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originalReportIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginalReportIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OriginalReportIn }
     * 
     * 
     */
    public List<OriginalReportIn> getOriginalReportIn() {
        if (originalReportIn == null) {
            originalReportIn = new ArrayList<OriginalReportIn>();
        }
        return this.originalReportIn;
    }

    /**
     * Gets the value of the reprintOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reprintOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReprintOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReprintOf }
     * 
     * 
     */
    public List<ReprintOf> getReprintOf() {
        if (reprintOf == null) {
            reprintOf = new ArrayList<ReprintOf>();
        }
        return this.reprintOf;
    }

    /**
     * Gets the value of the reprintIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reprintIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReprintIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReprintIn }
     * 
     * 
     */
    public List<ReprintIn> getReprintIn() {
        if (reprintIn == null) {
            reprintIn = new ArrayList<ReprintIn>();
        }
        return this.reprintIn;
    }

}
