//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 01:03:34 AM EDT 
//


package org.mindinformatics.services.connector.pubmed.fetch;

import javax.xml.bind.annotation.XmlRegistry;




/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mindinformatics.swan.pubmed.service.fetch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mindinformatics.swan.pubmed.service.fetch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MeshHeading }
     * 
     */
    public MeshHeading createMeshHeading() {
        return new MeshHeading();
    }

    /**
     * Create an instance of {@link CommentOn }
     * 
     */
    public CommentOn createCommentOn() {
        return new CommentOn();
    }

    /**
     * Create an instance of {@link DataBankName }
     * 
     */
    public DataBankName createDataBankName() {
        return new DataBankName();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link NlmDcmsID }
     * 
     */
    public NlmDcmsID createNlmDcmsID() {
        return new NlmDcmsID();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link PlaceCode }
     * 
     */
    public PlaceCode createPlaceCode() {
        return new PlaceCode();
    }

    /**
     * Create an instance of {@link DescriptorName }
     * 
     */
    public DescriptorName createDescriptorName() {
        return new DescriptorName();
    }

    /**
     * Create an instance of {@link ArticleIdList }
     * 
     */
    public ArticleIdList createArticleIdList() {
        return new ArticleIdList();
    }

    /**
     * Create an instance of {@link PublicationInfo }
     * 
     */
    public PublicationInfo createPublicationInfo() {
        return new PublicationInfo();
    }

    /**
     * Create an instance of {@link Imprint }
     * 
     */
    public Imprint createImprint() {
        return new Imprint();
    }

    /**
     * Create an instance of {@link Minute }
     * 
     */
    public Minute createMinute() {
        return new Minute();
    }

    /**
     * Create an instance of {@link TitleAssociatedWithName }
     * 
     */
    public TitleAssociatedWithName createTitleAssociatedWithName() {
        return new TitleAssociatedWithName();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Chemical }
     * 
     */
    public Chemical createChemical() {
        return new Chemical();
    }

    /**
     * Create an instance of {@link PubmedData }
     * 
     */
    public PubmedData createPubmedData() {
        return new PubmedData();
    }

    /**
     * Create an instance of {@link AccessionNumber }
     * 
     */
    public AccessionNumber createAccessionNumber() {
        return new AccessionNumber();
    }

    /**
     * Create an instance of {@link SummaryForPatientsIn }
     * 
     */
    public SummaryForPatientsIn createSummaryForPatientsIn() {
        return new SummaryForPatientsIn();
    }

    /**
     * Create an instance of {@link PublicationEndYear }
     * 
     */
    public PublicationEndYear createPublicationEndYear() {
        return new PublicationEndYear();
    }

    /**
     * Create an instance of {@link PMID }
     * 
     */
    public PMID createPMID() {
        return new PMID();
    }

    /**
     * Create an instance of {@link PublicationType }
     * 
     */
    public PublicationType createPublicationType() {
        return new PublicationType();
    }

    /**
     * Create an instance of {@link ArticleTitle }
     * 
     */
    public ArticleTitle createArticleTitle() {
        return new ArticleTitle();
    }

    /**
     * Create an instance of {@link PublicationStatus }
     * 
     */
    public PublicationStatus createPublicationStatus() {
        return new PublicationStatus();
    }

    /**
     * Create an instance of {@link DateCreated }
     * 
     */
    public DateCreated createDateCreated() {
        return new DateCreated();
    }

    /**
     * Create an instance of {@link RetractionIn }
     * 
     */
    public RetractionIn createRetractionIn() {
        return new RetractionIn();
    }

    /**
     * Create an instance of {@link ISSN }
     * 
     */
    public ISSN createISSN() {
        return new ISSN();
    }

    /**
     * Create an instance of {@link DateCompleted }
     * 
     */
    public DateCompleted createDateCompleted() {
        return new DateCompleted();
    }

    /**
     * Create an instance of {@link ErratumFor }
     * 
     */
    public ErratumFor createErratumFor() {
        return new ErratumFor();
    }

    /**
     * Create an instance of {@link ErratumIn }
     * 
     */
    public ErratumIn createErratumIn() {
        return new ErratumIn();
    }

    /**
     * Create an instance of {@link RetractionOf }
     * 
     */
    public RetractionOf createRetractionOf() {
        return new RetractionOf();
    }

    /**
     * Create an instance of {@link BroadJournalHeadingList }
     * 
     */
    public BroadJournalHeadingList createBroadJournalHeadingList() {
        return new BroadJournalHeadingList();
    }

    /**
     * Create an instance of {@link ForeName }
     * 
     */
    public ForeName createForeName() {
        return new ForeName();
    }

    /**
     * Create an instance of {@link NCBIArticle }
     * 
     */
    public NCBIArticle createNCBIArticle() {
        return new NCBIArticle();
    }

    /**
     * Create an instance of {@link CommentIn }
     * 
     */
    public CommentIn createCommentIn() {
        return new CommentIn();
    }

    /**
     * Create an instance of {@link GrantList }
     * 
     */
    public GrantList createGrantList() {
        return new GrantList();
    }

    /**
     * Create an instance of {@link RepublishedFrom }
     * 
     */
    public RepublishedFrom createRepublishedFrom() {
        return new RepublishedFrom();
    }

    /**
     * Create an instance of {@link NumberOfReferences }
     * 
     */
    public NumberOfReferences createNumberOfReferences() {
        return new NumberOfReferences();
    }

    /**
     * Create an instance of {@link OtherID }
     * 
     */
    public OtherID createOtherID() {
        return new OtherID();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link CommentsCorrections }
     * 
     */
    public CommentsCorrections createCommentsCorrections() {
        return new CommentsCorrections();
    }

    /**
     * Create an instance of {@link Hour }
     * 
     */
    public Hour createHour() {
        return new Hour();
    }

    /**
     * Create an instance of {@link DeleteCitation }
     * 
     */
    public DeleteCitation createDeleteCitation() {
        return new DeleteCitation();
    }

    /**
     * Create an instance of {@link PubmedArticle }
     * 
     */
    public PubmedArticle createPubmedArticle() {
        return new PubmedArticle();
    }

    /**
     * Create an instance of {@link CopyrightInformation }
     * 
     */
    public CopyrightInformation createCopyrightInformation() {
        return new CopyrightInformation();
    }

    /**
     * Create an instance of {@link PersonalNameSubjectList }
     * 
     */
    public PersonalNameSubjectList createPersonalNameSubjectList() {
        return new PersonalNameSubjectList();
    }

    /**
     * Create an instance of {@link QualifierName }
     * 
     */
    public QualifierName createQualifierName() {
        return new QualifierName();
    }

    /**
     * Create an instance of {@link NameQualifier }
     * 
     */
    public NameQualifier createNameQualifier() {
        return new NameQualifier();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link OtherAbstract }
     * 
     */
    public OtherAbstract createOtherAbstract() {
        return new OtherAbstract();
    }

    /**
     * Create an instance of {@link Grant }
     * 
     */
    public Grant createGrant() {
        return new Grant();
    }

    /**
     * Create an instance of {@link MedlineCitation }
     * 
     */
    public MedlineCitation createMedlineCitation() {
        return new MedlineCitation();
    }

    /**
     * Create an instance of {@link SpaceFlightMission }
     * 
     */
    public SpaceFlightMission createSpaceFlightMission() {
        return new SpaceFlightMission();
    }

    /**
     * Create an instance of {@link UpdateIn }
     * 
     */
    public UpdateIn createUpdateIn() {
        return new UpdateIn();
    }

    /**
     * Create an instance of {@link GeneSymbol }
     * 
     */
    public GeneSymbol createGeneSymbol() {
        return new GeneSymbol();
    }

    /**
     * Create an instance of {@link Issue }
     * 
     */
    public Issue createIssue() {
        return new Issue();
    }

    /**
     * Create an instance of {@link CollectionTitle }
     * 
     */
    public CollectionTitle createCollectionTitle() {
        return new CollectionTitle();
    }

    /**
     * Create an instance of {@link ISOAbbreviation }
     * 
     */
    public ISOAbbreviation createISOAbbreviation() {
        return new ISOAbbreviation();
    }

    /**
     * Create an instance of {@link RefSource }
     * 
     */
    public RefSource createRefSource() {
        return new RefSource();
    }

    /**
     * Create an instance of {@link GrantID }
     * 
     */
    public GrantID createGrantID() {
        return new GrantID();
    }

    /**
     * Create an instance of {@link ReprintIn }
     * 
     */
    public ReprintIn createReprintIn() {
        return new ReprintIn();
    }

    /**
     * Create an instance of {@link BroadJournalHeading }
     * 
     */
    public BroadJournalHeading createBroadJournalHeading() {
        return new BroadJournalHeading();
    }

    /**
     * Create an instance of {@link DataBankList }
     * 
     */
    public DataBankList createDataBankList() {
        return new DataBankList();
    }

    /**
     * Create an instance of {@link AccessionNumberList }
     * 
     */
    public AccessionNumberList createAccessionNumberList() {
        return new AccessionNumberList();
    }

    /**
     * Create an instance of {@link Second }
     * 
     */
    public Second createSecond() {
        return new Second();
    }

    /**
     * Create an instance of {@link Acronym }
     * 
     */
    public Acronym createAcronym() {
        return new Acronym();
    }

    /**
     * Create an instance of {@link NlmUniqueID }
     * 
     */
    public NlmUniqueID createNlmUniqueID() {
        return new NlmUniqueID();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link MedlineTA }
     * 
     */
    public MedlineTA createMedlineTA() {
        return new MedlineTA();
    }

    /**
     * Create an instance of {@link UpdateOf }
     * 
     */
    public UpdateOf createUpdateOf() {
        return new UpdateOf();
    }

    /**
     * Create an instance of {@link PubMedPubDate }
     * 
     */
    public PubMedPubDate createPubMedPubDate() {
        return new PubMedPubDate();
    }

    /**
     * Create an instance of {@link PublicationTypeList }
     * 
     */
    public PublicationTypeList createPublicationTypeList() {
        return new PublicationTypeList();
    }

    /**
     * Create an instance of {@link PartialRetractionIn }
     * 
     */
    public PartialRetractionIn createPartialRetractionIn() {
        return new PartialRetractionIn();
    }

    /**
     * Create an instance of {@link Affiliation }
     * 
     */
    public Affiliation createAffiliation() {
        return new Affiliation();
    }

    /**
     * Create an instance of {@link Frequency }
     * 
     */
    public Frequency createFrequency() {
        return new Frequency();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link ArticleId }
     * 
     */
    public ArticleId createArticleId() {
        return new ArticleId();
    }

    /**
     * Create an instance of {@link OtherInformation }
     * 
     */
    public OtherInformation createOtherInformation() {
        return new OtherInformation();
    }

    /**
     * Create an instance of {@link StartPage }
     * 
     */
    public StartPage createStartPage() {
        return new StartPage();
    }

    /**
     * Create an instance of {@link Pagination }
     * 
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link ChemicalList }
     * 
     */
    public ChemicalList createChemicalList() {
        return new ChemicalList();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link ArticleDate }
     * 
     */
    public ArticleDate createArticleDate() {
        return new ArticleDate();
    }

    /**
     * Create an instance of {@link PubmedArticleSet }
     * 
     */
    public PubmedArticleSet createPubmedArticleSet() {
        return new PubmedArticleSet();
    }

    /**
     * Create an instance of {@link MeshHeadingList }
     * 
     */
    public MeshHeadingList createMeshHeadingList() {
        return new MeshHeadingList();
    }

    /**
     * Create an instance of {@link JournalIssue }
     * 
     */
    public JournalIssue createJournalIssue() {
        return new JournalIssue();
    }

    /**
     * Create an instance of {@link MedlineJournalInfo }
     * 
     */
    public MedlineJournalInfo createMedlineJournalInfo() {
        return new MedlineJournalInfo();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link KeywordList }
     * 
     */
    public KeywordList createKeywordList() {
        return new KeywordList();
    }

    /**
     * Create an instance of {@link MedlineCitationSet }
     * 
     */
    public MedlineCitationSet createMedlineCitationSet() {
        return new MedlineCitationSet();
    }

    /**
     * Create an instance of {@link RegistryNumber }
     * 
     */
    public RegistryNumber createRegistryNumber() {
        return new RegistryNumber();
    }

    /**
     * Create an instance of {@link GeneralNote }
     * 
     */
    public GeneralNote createGeneralNote() {
        return new GeneralNote();
    }

    /**
     * Create an instance of {@link NameOfSubstance }
     * 
     */
    public NameOfSubstance createNameOfSubstance() {
        return new NameOfSubstance();
    }

    /**
     * Create an instance of {@link MedlineDate }
     * 
     */
    public MedlineDate createMedlineDate() {
        return new MedlineDate();
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link Investigator }
     * 
     */
    public Investigator createInvestigator() {
        return new Investigator();
    }

    /**
     * Create an instance of {@link Month }
     * 
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link Season }
     * 
     */
    public Season createSeason() {
        return new Season();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Agency }
     * 
     */
    public Agency createAgency() {
        return new Agency();
    }

    /**
     * Create an instance of {@link DatesOfSerialPublication }
     * 
     */
    public DatesOfSerialPublication createDatesOfSerialPublication() {
        return new DatesOfSerialPublication();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link DataBank }
     * 
     */
    public DataBank createDataBank() {
        return new DataBank();
    }

    /**
     * Create an instance of {@link OriginalReportIn }
     * 
     */
    public OriginalReportIn createOriginalReportIn() {
        return new OriginalReportIn();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link GeneSymbolList }
     * 
     */
    public GeneSymbolList createGeneSymbolList() {
        return new GeneSymbolList();
    }

    /**
     * Create an instance of {@link EndPage }
     * 
     */
    public EndPage createEndPage() {
        return new EndPage();
    }

    /**
     * Create an instance of {@link DatesAssociatedWithName }
     * 
     */
    public DatesAssociatedWithName createDatesAssociatedWithName() {
        return new DatesAssociatedWithName();
    }

    /**
     * Create an instance of {@link ReprintOf }
     * 
     */
    public ReprintOf createReprintOf() {
        return new ReprintOf();
    }

    /**
     * Create an instance of {@link InvestigatorList }
     * 
     */
    public InvestigatorList createInvestigatorList() {
        return new InvestigatorList();
    }

    /**
     * Create an instance of {@link DateRevised }
     * 
     */
    public DateRevised createDateRevised() {
        return new DateRevised();
    }

    /**
     * Create an instance of {@link RepublishedIn }
     * 
     */
    public RepublishedIn createRepublishedIn() {
        return new RepublishedIn();
    }

    /**
     * Create an instance of {@link CollectiveName }
     * 
     */
    public CollectiveName createCollectiveName() {
        return new CollectiveName();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link VernacularTitle }
     * 
     */
    public VernacularTitle createVernacularTitle() {
        return new VernacularTitle();
    }

    /**
     * Create an instance of {@link ProjectedPublicationDate }
     * 
     */
    public ProjectedPublicationDate createProjectedPublicationDate() {
        return new ProjectedPublicationDate();
    }

    /**
     * Create an instance of {@link MiddleName }
     * 
     */
    public MiddleName createMiddleName() {
        return new MiddleName();
    }

    /**
     * Create an instance of {@link FirstName }
     * 
     */
    public FirstName createFirstName() {
        return new FirstName();
    }

    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link LastName }
     * 
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link Edition }
     * 
     */
    public Edition createEdition() {
        return new Edition();
    }

    /**
     * Create an instance of {@link AbstractText }
     * 
     */
    public AbstractText createAbstractText() {
        return new AbstractText();
    }

    /**
     * Create an instance of {@link MedlinePgn }
     * 
     */
    public MedlinePgn createMedlinePgn() {
        return new MedlinePgn();
    }

    /**
     * Create an instance of {@link PersonalNameSubject }
     * 
     */
    public PersonalNameSubject createPersonalNameSubject() {
        return new PersonalNameSubject();
    }

    /**
     * Create an instance of {@link AuthorList }
     * 
     */
    public AuthorList createAuthorList() {
        return new AuthorList();
    }

    /**
     * Create an instance of {@link DateIssued }
     * 
     */
    public DateIssued createDateIssued() {
        return new DateIssued();
    }

    /**
     * Create an instance of {@link PubDate }
     * 
     */
    public PubDate createPubDate() {
        return new PubDate();
    }

    /**
     * Create an instance of {@link Coverage }
     * 
     */
    public Coverage createCoverage() {
        return new Coverage();
    }

    /**
     * Create an instance of {@link Initials }
     * 
     */
    public Initials createInitials() {
        return new Initials();
    }

    /**
     * Create an instance of {@link Coden }
     * 
     */
    public Coden createCoden() {
        return new Coden();
    }

    /**
     * Create an instance of {@link CitationSubset }
     * 
     */
    public CitationSubset createCitationSubset() {
        return new CitationSubset();
    }

    /**
     * Create an instance of {@link PublicationFirstYear }
     * 
     */
    public PublicationFirstYear createPublicationFirstYear() {
        return new PublicationFirstYear();
    }

    /**
     * Create an instance of {@link Suffix }
     * 
     */
    public Suffix createSuffix() {
        return new Suffix();
    }

    /**
     * Create an instance of {@link PartialRetractionOf }
     * 
     */
    public PartialRetractionOf createPartialRetractionOf() {
        return new PartialRetractionOf();
    }

}
