//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 01:03:34 AM EDT 
//


package org.mindinformatics.services.connector.pubmed.fetch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Country" minOccurs="0"/>
 *         &lt;element ref="{}PlaceCode" minOccurs="0"/>
 *         &lt;element ref="{}Imprint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Place" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Publisher" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}DateIssued" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ProjectedPublicationDate" minOccurs="0"/>
 *         &lt;element ref="{}PublicationFirstYear" minOccurs="0"/>
 *         &lt;element ref="{}PublicationEndYear" minOccurs="0"/>
 *         &lt;element ref="{}Edition" minOccurs="0"/>
 *         &lt;element ref="{}DatesOfSerialPublication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Frequency" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "country",
    "placeCode",
    "imprint",
    "place",
    "publisher",
    "dateIssued",
    "projectedPublicationDate",
    "publicationFirstYear",
    "publicationEndYear",
    "edition",
    "datesOfSerialPublication",
    "frequency"
})
@XmlRootElement(name = "PublicationInfo")
public class PublicationInfo {

    @XmlElement(name = "Country")
    protected Country country;
    @XmlElement(name = "PlaceCode")
    protected PlaceCode placeCode;
    @XmlElement(name = "Imprint")
    protected List<Imprint> imprint;
    @XmlElement(name = "Place")
    protected List<Place> place;
    @XmlElement(name = "Publisher")
    protected List<Publisher> publisher;
    @XmlElement(name = "DateIssued")
    protected List<DateIssued> dateIssued;
    @XmlElement(name = "ProjectedPublicationDate")
    protected ProjectedPublicationDate projectedPublicationDate;
    @XmlElement(name = "PublicationFirstYear")
    protected PublicationFirstYear publicationFirstYear;
    @XmlElement(name = "PublicationEndYear")
    protected PublicationEndYear publicationEndYear;
    @XmlElement(name = "Edition")
    protected Edition edition;
    @XmlElement(name = "DatesOfSerialPublication")
    protected List<DatesOfSerialPublication> datesOfSerialPublication;
    @XmlElement(name = "Frequency")
    protected List<Frequency> frequency;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountry(Country value) {
        this.country = value;
    }

    /**
     * Gets the value of the placeCode property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceCode }
     *     
     */
    public PlaceCode getPlaceCode() {
        return placeCode;
    }

    /**
     * Sets the value of the placeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceCode }
     *     
     */
    public void setPlaceCode(PlaceCode value) {
        this.placeCode = value;
    }

    /**
     * Gets the value of the imprint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imprint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImprint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Imprint }
     * 
     * 
     */
    public List<Imprint> getImprint() {
        if (imprint == null) {
            imprint = new ArrayList<Imprint>();
        }
        return this.imprint;
    }

    /**
     * Gets the value of the place property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the place property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Place }
     * 
     * 
     */
    public List<Place> getPlace() {
        if (place == null) {
            place = new ArrayList<Place>();
        }
        return this.place;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Publisher }
     * 
     * 
     */
    public List<Publisher> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<Publisher>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the dateIssued property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateIssued property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateIssued().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateIssued }
     * 
     * 
     */
    public List<DateIssued> getDateIssued() {
        if (dateIssued == null) {
            dateIssued = new ArrayList<DateIssued>();
        }
        return this.dateIssued;
    }

    /**
     * Gets the value of the projectedPublicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectedPublicationDate }
     *     
     */
    public ProjectedPublicationDate getProjectedPublicationDate() {
        return projectedPublicationDate;
    }

    /**
     * Sets the value of the projectedPublicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectedPublicationDate }
     *     
     */
    public void setProjectedPublicationDate(ProjectedPublicationDate value) {
        this.projectedPublicationDate = value;
    }

    /**
     * Gets the value of the publicationFirstYear property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationFirstYear }
     *     
     */
    public PublicationFirstYear getPublicationFirstYear() {
        return publicationFirstYear;
    }

    /**
     * Sets the value of the publicationFirstYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationFirstYear }
     *     
     */
    public void setPublicationFirstYear(PublicationFirstYear value) {
        this.publicationFirstYear = value;
    }

    /**
     * Gets the value of the publicationEndYear property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationEndYear }
     *     
     */
    public PublicationEndYear getPublicationEndYear() {
        return publicationEndYear;
    }

    /**
     * Sets the value of the publicationEndYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationEndYear }
     *     
     */
    public void setPublicationEndYear(PublicationEndYear value) {
        this.publicationEndYear = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link Edition }
     *     
     */
    public Edition getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Edition }
     *     
     */
    public void setEdition(Edition value) {
        this.edition = value;
    }

    /**
     * Gets the value of the datesOfSerialPublication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datesOfSerialPublication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatesOfSerialPublication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatesOfSerialPublication }
     * 
     * 
     */
    public List<DatesOfSerialPublication> getDatesOfSerialPublication() {
        if (datesOfSerialPublication == null) {
            datesOfSerialPublication = new ArrayList<DatesOfSerialPublication>();
        }
        return this.datesOfSerialPublication;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frequency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrequency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Frequency }
     * 
     * 
     */
    public List<Frequency> getFrequency() {
        if (frequency == null) {
            frequency = new ArrayList<Frequency>();
        }
        return this.frequency;
    }

}
