//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 01:03:34 AM EDT 
//


package org.mindinformatics.services.connector.pubmed.fetch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="lang">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="PL"/>
 *             &lt;enumeration value="PS"/>
 *             &lt;enumeration value="PT"/>
 *             &lt;enumeration value="EL"/>
 *             &lt;enumeration value="EN"/>
 *             &lt;enumeration value="FA"/>
 *             &lt;enumeration value="ES"/>
 *             &lt;enumeration value="FI"/>
 *             &lt;enumeration value="RO"/>
 *             &lt;enumeration value="FR"/>
 *             &lt;enumeration value="RU"/>
 *             &lt;enumeration value="SK"/>
 *             &lt;enumeration value="SL"/>
 *             &lt;enumeration value="SQ"/>
 *             &lt;enumeration value="SR"/>
 *             &lt;enumeration value="SV"/>
 *             &lt;enumeration value="HE"/>
 *             &lt;enumeration value="SW"/>
 *             &lt;enumeration value="TH"/>
 *             &lt;enumeration value="TR"/>
 *             &lt;enumeration value="HU"/>
 *             &lt;enumeration value="HY"/>
 *             &lt;enumeration value="UK"/>
 *             &lt;enumeration value="IN"/>
 *             &lt;enumeration value="JA"/>
 *             &lt;enumeration value="IS"/>
 *             &lt;enumeration value="IT"/>
 *             &lt;enumeration value="IW"/>
 *             &lt;enumeration value="VI"/>
 *             &lt;enumeration value="KA"/>
 *             &lt;enumeration value="KO"/>
 *             &lt;enumeration value="LT"/>
 *             &lt;enumeration value="AF"/>
 *             &lt;enumeration value="MK"/>
 *             &lt;enumeration value="ML"/>
 *             &lt;enumeration value="AR"/>
 *             &lt;enumeration value="ZH"/>
 *             &lt;enumeration value="BG"/>
 *             &lt;enumeration value="AZ"/>
 *             &lt;enumeration value="NL"/>
 *             &lt;enumeration value="NO"/>
 *             &lt;enumeration value="DA"/>
 *             &lt;enumeration value="CS"/>
 *             &lt;enumeration value="DE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="fulltext"/>
 *             &lt;enumeration value="FullText"/>
 *             &lt;enumeration value="Summary"/>
 *             &lt;enumeration value="summary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "URL")
public class URL {

    @XmlValue
    protected String content;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;
    @XmlAttribute(name = "Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
